name: The Commute Podcast
description: Music for your commute.
url: http://commute.pwenzel.info
author: Paul Wenzel
author-email: paul@pwenzel.info
feed-url: http://feeds.feedburner.com/CommutePodcast
feed-image: http://m.pwenzel.info/podcasts/commute_1400x1400.jpg